---
path: prepared

versions:
  - 1.9.6
  - 2.0.2
  - 2.1.3
  - 2.2.0

tests:
  - name: Testing template performance
    templates: 100
  - name: Testing big stack of variables
    vars: 1000
    templates: 100
  - name: Testing shell execution with register
    executions: 100
